apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ required "redis.password 값이 필요합니다" .Values.redis.password | b64enc | quote }}
