# ArgoCD NAS (NFS) Persistence Manifest
# Usage: Change 'server' and 'path', then run 'kubectl apply -f nas-pv.yaml'

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100  # <--- NAS Server IP 변경
    path: /nas/argocd/redis # <--- NAS 경로 변경
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-redis-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: argocd-redis-pv
  storageClassName: "" # Static binding

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-repo-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.100  # <--- NAS Server IP 변경
    path: /nas/argocd/repo  # <--- NAS 경로 변경
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-repo-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: argocd-repo-pv
  storageClassName: "" # Static binding
