# 배포 방식 — DaemonSet(멀티 노드) 또는 Deployment(단일 노드)
envoy:
  deploymentType: DaemonSet

# 서비스 노출 방식
# LoadBalancer : type: LoadBalancer, proxyProtocol: false
# NodePort(HAProxy 앞단) : type: NodePort, proxyProtocol: true
service:
  type: LoadBalancer
  trafficPolicy: Local

clientIP:
  proxyProtocol: false
