apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pvc
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cmsk8s
  resources:
    requests:
      storage: 100Gi
