# 공통 설정
common:
  namespace: envoy-gateway-system

gateway:
  name: "cluster-gateway" # 기본값 (스크립트에서 덮어쓸 예정)
  tls:
    name: "gateway-tls"

service:
  trafficPolicy: Local
  type: LoadBalancer

envoy:
  nodeName: "" # 스크립트에서 주입
  image: "docker.io/envoyproxy/envoy:distroless-v1.36.3"
  deploymentType: DaemonSet # "Deployment" 또는 "DaemonSet" (멀티 노드 환경)

clientIP:
  proxyProtocol: false # true 시 HAProxy 앞단 필수 (NodePort 직접 접근 차단됨)