image:
  repository: openpolicyagent/gatekeeper
  crdRepository: openpolicyagent/gatekeeper-crds
  release: v3.17.0
  pullPolicy: IfNotPresent

replicas: 3

audit:
  interval: 60
  emitAuditEvents: true

controllerManager:
  exemptNamespaces:
    - kube-system
    - gatekeeper-system
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

postInstall:
  labelNamespace:
    enabled: false

preUninstall:
  deleteWebhookConfigurations:
    enabled: true
