# Cilium 1.19.3 Local Values (for Local Tar Import)
image:
  repository: "quay.io/cilium/cilium"
  tag: "v1.19.3"
  pullPolicy: "IfNotPresent"

operator:
  image:
    repository: "quay.io/cilium/operator-generic"
    tag: "v1.19.3"
    pullPolicy: "IfNotPresent"

hubble:
  hubble:
    enabled: true
    relay:
      enabled: false # Managed by install.sh --set
      image:
        repository: "quay.io/cilium/hubble-relay"
        tag: "v1.19.3"
    ui:
      enabled: false # Managed by install.sh --set
      backend:
        image:
          repository: "quay.io/cilium/hubble-ui-backend"
          tag: "v0.13.3"
      frontend:
        image:
          repository: "quay.io/cilium/hubble-ui"
          tag: "v0.13.3"

  envoy:
    image:
      repository: "quay.io/cilium/cilium-envoy"
      tag: "v1.36.6-1776000132-2437d2edeaf4d9b56ef279bd0d71127440c067aa"


kubeProxyReplacement: true

# Use standard defaults for local testing
ipam:
  mode: "cluster-pool"
