apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-stream-master-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: redis-stream
    name: redis-data-redis-stream-master-0
  hostPath:
    path: __BASE_PATH__/master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "__NODE_NAME__"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-stream-replica-0-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: redis-stream
    name: redis-data-redis-stream-replicas-0
  hostPath:
    path: __BASE_PATH__/replica-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "__NODE_NAME__"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-stream-replica-1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: redis-stream
    name: redis-data-redis-stream-replicas-1
  hostPath:
    path: __BASE_PATH__/replica-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "__NODE_NAME__"
