apiVersion: v1
kind: Pod
metadata:
  name: redis-stream-test
  namespace: redis-stream
spec:
  containers:
  - name: redis-cli
    image: __TEST_IMAGE__
    command: ["sleep", "infinity"]
  restartPolicy: Never
