# Generated bundle install configuration template.

K8S_VERSION="{{K8S_VERSION}}"
TARGET_OS="{{TARGET_OS}}"
ARCH="{{ARCH}}"

CONTAINER_RUNTIME="{{CONTAINER_RUNTIME}}"
CONTAINERD_VERSION="{{CONTAINERD_VERSION}}"

CNI_CHOICE="{{CNI_CHOICE}}"
CALICO_VERSION="{{CALICO_VERSION}}"
CALICO_INSTALL_METHOD="{{CALICO_INSTALL_METHOD}}"
CILIUM_VERSION="{{CILIUM_VERSION}}"
