apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100
    path: /nas/jenkins
