apiVersion: v1
kind: Secret
metadata:
  name: harbor-regcred
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.devops.internal:30002": {
          "username": "admin",
          "password": "CHANGE_ME",
          "auth": "CHANGE_ME_BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
