apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.sentinelHeadlessName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "redis-sentinel.sentinelName" . }}
  ports:
  - name: sentinel
    port: 26379
    targetPort: 26379
