apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-secret
  namespace: trident
type: Opaque
stringData:
  username: "vsadmin"
  password: "$qkfahr55"
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas-v3
  namespace: trident
spec:
  version: 1
  storageDriverName: "ontap-nas"
  managementLIF: "172.16.126.148"
  dataLIF: "172.16.126.147"
  svm: "LGEHQ_K8S1_CMP"
  storagePrefix: "k8s_cmp_"
  credentials:
    name: backend-tbc-ontap-secret
  defaults:
    spaceReserve: "none"
    encryption: "false"
