apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas-v3-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
  - hard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas-v3-sc-retain
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
  - hard

