apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-v3-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ontap-nas-v3-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-v3-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo 'NetApp Trident NFSv3 Dynamic Provisioning Success!;' > /data/test.txt && tail -f /dev/null"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /data
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-v3-test-pvc
